### ISSUE TITLE
DarTask doAfterEvaluate() does work during configuration and breaks UP-TO-DATE checking

### ISSUE THREAD

**Issue by flstaats** [xebialabs-community/gradle-xld-plugin#10]
As implemented DarTask doAfterEvaluate() can do real work during the configuration stage.  This is a problem in that a build that does not involve running the DarTask will still do the work of processing the manifest file.  The performance hit in a large project with many subprojects with the gradle-xld-plugin can be significant.

Also the DarTask does not properly declare it's inputs and outputs so UP-TO-DATE checking is broken.  You can see this in that it takes three "build" runs before the DarTask stabilizes as UP-TO-DATE.

The way to fix this is to move the processManifest() processing into a separate task with it's own inputs and outputs and declare the DarTask as dependsOn() on the new task.  Then all the work will be done execution time rather than configuration time and UP-TO-DATE checking will work correctly.

**Comment by flstaats** [comment]
Note the PR currently awaiting approval for Issue #11 addresses most of these issues.  That PR has some problems with building on Java 1.7 but I added a comment on changing the dependencies to fix that.

**Comment by jdewinne** [comment]
I've now released [v0.5.0](https://plugins.gradle.org/plugin/com.xebialabs.xl-deploy). Thanks for all the hard work!
