### ISSUE TITLE
Failed to import dar package

### ISSUE THREAD

**Issue by fowlie** [xebialabs-community/gradle-xld-plugin#4]
Hi.

We are using the maven plugin to create dar packages and to import them into XL Deploy 4.5.3. This plugin creates a dar package with all our war files in a flat-structured way.

I tried this plugin and it looks very promising, but I'm getting an error when the plugin tries to import the dar package: 

``` java
com.xebialabs.deployit.exception.RuntimeIOException: The file artifacts\webshop-animal\build\libs/webshop-animal.war could not be found in the package.
```

All the war files are like you can see, wrapped into artifacts<module_name>\build\libs/<module_name>.war. The path is correct and the war file exists in the dar package. I guess it could be the forward slash at the end? Any ideas?

PS, We use a multi-project gradle setup, and the manifest file looks like this (truncated):

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<udm.DeploymentPackage version="${project.property('xldeploy-version')}" application="webshop-deployit-bundle">
    <deployables>
        <was.War name="webshop-animal" file="${artifact(project.findProject('webshop-animal').war)}">
            <excludeFileNamesRegex>.+\\.(jar)</excludeFileNamesRegex>
            <scanPlaceholders>true</scanPlaceholders>
            <contextRoot>/webshop-animal</contextRoot>
            <virtualHostName>intranet_host</virtualHostName>
            <classloaderMode>PARENT_LAST</classloaderMode>
            <warClassloaderMode>PARENT_LAST</warClassloaderMode>
        </was.War>
    </deployables>
</udm.DeploymentPackage>
```

**Comment by byaminov** [comment]
@fowlie sorry for a late answer. I think you are right, it could be a problem with forward slashes. Could you please try updating the generated manifest.xml file by replacing `\` with `/` and then import into XL Deploy manually? And let me know if it fixes the problem?

Thanks in advance.

**Comment by fowlie** [comment]
Thanks for the tip. I'll have to get back to you about this when I get more time to work on this issue, maybe beginning of next month.

**Comment by fowlie** [comment]
I just tried your idea and it worked. Do you have any ideas on how to fix it?

**Comment by byaminov** [comment]
@fowlie I fixed the bug with Windows paths and released a new version: [0.2.2](https://plugins.gradle.org/plugin/com.xebialabs.xl-deploy/0.2.2). Please let me know if this does not fix your issue!

**Comment by fowlie** [comment]
Thanks, but I can't find the new 0.2.2 version in the public repo. Is it just me, or is it possible that the publication is not done yet?

**Comment by byaminov** [comment]
Which public repo do you mean? The plugin is published to the plugins.gradle.com: https://plugins.gradle.org/plugin/com.xebialabs.xl-deploy/0.2.2 , so it's downloaded from there once you add the plugin to your project.

You still need to configure additional repositories, as some dependencies come from there, like this:

```
buildscript {
  repositories {
    maven {
      url "http://www.knopflerfish.org/maven2/"
    }
    maven {
      url "https://dist.xebialabs.com/public/maven2/"
    }
  }
}
plugins {
  id "com.xebialabs.xl-deploy" version "0.2.2"
}
```

**Comment by fowlie** [comment]
We're using `apply plugin`and not `plugins`, so it was not clear for me that I needed to add `https://plugins.gradle.org/m2/` as a repository. Probably should be added to the documentation.

**Comment by byaminov** [comment]
Ah, right! Thanks for reporting. Gradle changed the way you can publish a plugin a couple of months ago :)

**Comment by fowlie** [comment]
I can't get this to work, I'm forced to use the company Nexus server since the build server doesn't have direct internett access (yeah we should probably do something about this, but...). And it seems that `https://plugins.gradle.org/m2/` is not possible to add as a proxy repo in Nexus for some reason. Could you please also publish version 0.2.2 to JCenter etc?

**Comment by byaminov** [comment]
Ok, it's published: https://bintray.com/xebialabs/maven/xl-deploy-gradle-plugin/0.2.2/view . Hope this helps!

**Comment by fowlie** [comment]
Thanks a lot! :smiley:

**Comment by maruthi199** [comment]
Hi byaminov,

i am unable to deploy my .dar file in to XLdeploy and i am getting below error.

com.xebialabs.deployit.ci.server.PluginFirstClassloaderInvocationHandler.doInvoke(PluginFirstClassloaderInvocationHandler.java:70)
	at com.xebialabs.deployit.ci.server.PluginFirstClassloaderInvocationHandler.invoke(PluginFirstClassloaderInvocationHandler.java:56)
	... 12 more
ERROR: Error when importing dar file workspace\sample\deployitpackage\sample-1.0.dar : java.lang.RuntimeException: Failed : HTTP error code : 500
Build step 'Deploy with XL Deploy' marked build as failure
Finished: FAILURE

please help out me with this error.

**Comment by byaminov** [comment]
Hi @maruthi199,

Seems like XL Deploy returns the `500` HTTP error when trying to import the `sample-1.0.dar`, but there is not any more information to find the reason in the log that you sent. Can you please check the XL Deploy server logs and see what exception occurs there? Maybe you will get a clue what's wrong with the DAR file.

Also can you please create a new GitHub issue for your question? Or do you believe that your error is related to the above discussion about Windows slashes and the way the Gradle plugin should be added?
