### ISSUE TITLE
deletePreviouslyDeployedDar : No such property

### ISSUE THREAD

**Issue by godojoe** [xebialabs-community/gradle-xld-plugin#8]
I am getting 
'No such property: deletePreviouslyDeployedDar for class: com.xebialabs.gradle.xldeploy.XlDeployPluginExtension_Decorated'

when running a 'clean dar deploy', with this config

```
xldeploy {
    xldUrl = xldeployUrl
    xldUsername = xldeployUsername
    xldPassword = xldeployPassword
    manifest = file('setupscripts\\xl_deploy\\deployit-manifest.xml')
    deletePreviouslyDeployedDar = true
}
```

**Comment by byaminov** [comment]
@godojoe the global `xldeploy { .. }` extension contains only five configuration properties now: the `manifest` and the XL Deploy connection details, you can see them in [XlDeployPluginExtension.groovy](https://github.com/xebialabs-community/gradle-xld-plugin/blob/master/src/main/groovy/com/xebialabs/gradle/xldeploy/XlDeployPluginExtension.groovy)

The `deletePreviouslyDeployedDar` is a configuration of the [`deploy` task](https://github.com/xebialabs-community/gradle-xld-plugin#deploy-task), so your example should be configured like following:

```
xldeploy {
  xldUrl = xldeployUrl
  xldUsername = xldeployUsername
  xldPassword = xldeployPassword
  manifest = file('setupscripts\\xl_deploy\\deployit-manifest.xml')
}

tasks.deploy.configure {
  deletePreviouslyDeployedDar = true
}
```

**Comment by godojoe** [comment]
thanks for that. This solves the 'No such property' error, however, the property does not seem to take effect (xldeploy server: 5.1.3, 
com.xebialabs.gradle:xl-deploy-gradle-plugin 0.2.3).
I get this when attempting to redeploy the same .dar:

```
error   18-Apr-2016 11:02:20    11:02:20.378 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':deploy'.
error   18-Apr-2016 11:02:20    11:02:20.378 [ERROR] [org.gradle.BuildExceptionReporter] > com.xebialabs.deployit.service.importer.ImporterException:Already imported version 0.1.dev0009-93-g3f42 of application ...
```

**Comment by byaminov** [comment]
@godojoe the `deletePreviouslyDeployedDar` flag makes sure that the _previous version_ of an application would be deleted after deploying a new version. So if you would deploy `my-app-1.0` and deploy `my-app-1.1`, then `my-app-1.0` would be deleted after successful deployment. Here is an example output:

```
:dar
:deploy
Importing dar file /Users/bulat/fun/gradle-xld-plugin/src/test/resources/HelloDeployment/build/libs/HelloDeployment-1.0.dar
Application already exists => preparing update
Executing generated deployment task: c23bfaad-7f4a-406d-a684-d9d29f112a0a (run Gradle with '-i' to see detailed output)
Removing the previous version Applications/HelloDeployment/1.0-20160415-222551
```

It is however not possible to redeploy the same version: `my-app-1.0`. 

If you are in development mode I suggest that you use a `-SNAPSHOT` suffix for your version, then on every build your `.dar` file will get a new version with a timestamp. See an example configuration of [`build.gradle`](https://github.com/xebialabs-community/gradle-xld-plugin/blob/master/src/test/resources/HelloDeployment/build.gradle#L18) and [`deployit-manifest.xml` with `noSnapshot` function](https://github.com/xebialabs-community/gradle-xld-plugin/blob/master/src/test/resources/HelloDeployment/src/main/dar/deployit-manifest.xml#L9). Once the development is finished then you can release the final `1.0`, deploy it once and switch to the next iteration, e.g. `1.1`.

**Comment by godojoe** [comment]
Got it. Problem solved. Thanks for the quick feedback.

**Comment by byaminov** [comment]
I'm glad it's solved!
