### ISSUE TITLE
windows MSI deployable support

### ISSUE THREAD

**Issue by godojoe** [xebialabs-community/gradle-xld-plugin#9]
Does the plugin support windows.Msi deployables?
If I use a manifest like this:
`<?xml version="1.0" encoding="UTF-8"?>
<udm.DeploymentPackage application="OurApplication" version="${noSnapshot("(package_version)s")}">
<orchestrator>
  <value>sequential-by-composite-package</value>
 </orchestrator>
<deployables>
<windows.Msi name="OurApplication-64bit" file="Setup/Release/OurApplication-64bit.msi">
</windows.Msi>                                
</deployables>
</udm.DeploymentPackage>    `
, 
the resulting dar package does not contain the .msi .

**Comment by jdewinne** [comment]
I haven't tried your manifest yet, but do you see an error message in the XLD log or when executing the gradle task?
Also could it be your `udm.DeploymentPackage` `version` attribute is incorrect? The `s` at the end might be wrong (`${noSnapshot("(package_version)s")}`)

**Comment by godojoe** [comment]
I don't see any errors in the gradle task:
To honour the JVM settings for this build a new JVM will be forked. Please
consider using the daemon:
http://gradle.org/docs/2.5/userguide/gradle_daemon.html.
[buildinfo] Not using buildInfo properties file for this build.
:clean
:dar

BUILD SUCCESSFUL

The udm.DeploymentPackage version needs to contain 's' - removing it
produces
' ValueError: unsupported format character '"' '

**Comment by godojoe** [comment]
Sorry, this was my error (path to the .msi was incorrect) - running with
--debug revealed that..
The plugin correctly includes the .msi in the .dar.
Thanks for the help.
